version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install phase"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Current Working Directory:" $(pwd) #troubleshoot with pwd
      - chmod +x webapp-script.sh terraform-apply.sh aws-credentials.sh
  build:
    commands:
      - echo "Build phase"
      #- ./webapp-script.sh
      - ./terraform-apply.sh
      - ./aws-credentials.sh