version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install phase"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      
  pre_build:
    commands:
      - echo "Current Working Directory:" $(pwd) #troubleshoot with pwd
      - cd shell-scripts
      - chmod +x webapp-script.sh terraform-apply.sh aws-credentials.sh
      - ./aws-credentials.sh
      - ./webapp-script.sh
  build:
    commands:
      - echo "Build phase"
      - aws configure set aws_access_key_id $access_key
      - aws configure set aws_secret_access_key $secret_key
      - aws configure set region $region_key
      - ./terraform-apply.sh